name: Run Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - "**"
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Get dependencies
        run: |
          go install github.com/kyoh86/richgo@latest
          go get -v -t -d ./...
      - name: Run tests
        id: tests
        run: richgo test -v -race -cover -bench=. ./...
        env:
          IN_TRAVIS_CI: yes
          RICHGO_FORCE_COLOR: 1
  summary:
    name: Summary Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Get dependencies
        run: |
          go install github.com/mfridman/tparse@latest
          go get -v -t -d ./...
      - name: Run tests
        id: tests
        run: go test -v -race -cover -json -bench=. ./... | tparse -notests -format=markdown >> $GITHUB_STEP_SUMMARY
        env:
          IN_TRAVIS_CI: yes
